### PR TITLE
Update all dependencies

### PR DESCRIPTION
**Pull request by johnlettman**
This PR updates all project dependencies in `pyproject.toml` to keep everything fresh and avoid potential dependency conflicts in user projects.

All tests continue to pass.

### CODE REVIEW

**Comment by avi-perl** [comment]
Thanks for submitting this! 

Appears tests are failing for some reason. Once we're here, I think it makes sense to add tests for the newer Python versions and extend official support.

Perhaps I'll have some time to look at this over the weekend, thanks for getting me started!

**Comment by johnlettman** [comment]
No worries! I would be happy to help wherever needed.
I notice the tests seem to fail with a dependency I wrangled with on my local branch:
```
/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_rich_tools.py:1: in <module>
    import toml
E   ModuleNotFoundError: No module named 'toml'
```

I'm not sure why, but doing `poetry install --with dev` didn't seem to pick it up.

**Comment by johnlettman** [comment]
Ohhh, I see.

The tests install from `requirements.txt`:
https://github.com/avi-perl/rich_tools/blob/b4a31a513928954f74440882b47e4a417fea0b7d/.github/workflows/test.yml#L24-L28

... but `toml` is not listed in `requirements.txt`: 
https://github.com/avi-perl/rich_tools/blob/b4a31a513928954f74440882b47e4a417fea0b7d/requirements.txt#L1-L9

... it is, however, listed in `pyproject.toml`:
https://github.com/avi-perl/rich_tools/blob/b4a31a513928954f74440882b47e4a417fea0b7d/pyproject.toml#L33

**Comment by avi-perl** [comment]
I cannot remember why I'd have relied on requirements.txt, it's entirely possible at the time I didn't know how, or didn't think, to use poetry to install dependencies. Changing the install process (and probably removing requirements) should fix this.

**Pull request closed without merging**
